### PR TITLE
add settings for note item status

### PR DESCRIPTION
**Pull request by AndryYosua**
While todo item has status `overdue`, `open` or `done`, note item do not has one.
This PR add settings for note item status

### Steps

- create a note and todo note
- create note-overview
  ```
  <!-- note-overview-plugin
  search: ...
  fields: status, title
  status:
    todo:
      open: "☐"
      done: "🗹"
      overdue: "⚠"
  -->
  ```

### Actual result

note status and todo status has same status

| status | title                                                   |
| ------ | ------------------------------------------------------- |
| ⚠      | [todo overdue](:/722c80cb665549fb94472d4802cfbdc5)      |
| 🗹      | [todo completed](:/6adfa0f5c5ab4642bc696db08a212baf)    |
| ☐      | [todo with duedate](:/27de5a7fa4424ad993c6ee251ee88812) |
| ☐      | [todo open](:/01bca8a69a9341cabcba59531c0cad8e)         |
| ☐      | [note 1](:/1809922cc3fa49c1bf8f045cbf6f8e55)            |

### Expected result

as note do not have status (`overdue`, `open` or `done`), note status should be empty.

| status | title                                                   |
| ------ | ------------------------------------------------------- |
| ⚠      | [todo overdue](:/722c80cb665549fb94472d4802cfbdc5)      |
| 🗹      | [todo completed](:/6adfa0f5c5ab4642bc696db08a212baf)    |
| ☐      | [todo with duedate](:/27de5a7fa4424ad993c6ee251ee88812) |
| ☐      | [todo open](:/01bca8a69a9341cabcba59531c0cad8e)         |
|        | [note 1](:/1809922cc3fa49c1bf8f045cbf6f8e55)            |

### Other Result
```
<!-- note-overview-plugin
search: ...
fields: status, title
status:
  note: "🗈"
  todo:
    open: "☐"
    done: "🗹"
    overdue: "⚠"
-->
  ```

| status | title                                                   |
| ------ | ------------------------------------------------------- |
| ⚠      | [todo overdue](:/722c80cb665549fb94472d4802cfbdc5)      |
| 🗹      | [todo completed](:/6adfa0f5c5ab4642bc696db08a212baf)    |
| ☐      | [todo with duedate](:/27de5a7fa4424ad993c6ee251ee88812) |
| ☐      | [todo open](:/01bca8a69a9341cabcba59531c0cad8e)         |
| 🗈       | [note 1](:/1809922cc3fa49c1bf8f045cbf6f8e55)            |

### CODE REVIEW

**Comment by aiosk** [comment]
maybe add `Field status: note` option to `Tools` > `Options` > `Note Overview` options?

**Comment by JackGruber** [comment]
Please create tests for the PR

**Comment by aiosk** [comment]
> Please create tests for the PR

done
i add documentation too

**Comment by JackGruber** [comment]
Please make the following adjustments: 

1) is_todo should only be added if it is needed 
https://github.com/JackGruber/joplin-plugin-note-overview/blob/736916f15a02eb94c41261b196cc5c6e20126bac/src/noteoverview.ts#L844-L848
2) The default option should also be adjustable in the settings, as the other options are also in the plugin settings section
3) Please note that the develop branch already has a translation!

I think then I can merge the PR

**Comment by aiosk** [comment]
> Please make the following adjustments:
> 
>     1. is_todo should only be added if it is needed
>        https://github.com/JackGruber/joplin-plugin-note-overview/blob/736916f15a02eb94c41261b196cc5c6e20126bac/src/noteoverview.ts#L844-L848
done

>     2. The default option should also be adjustable in the settings, as the other options are also in the plugin settings section
and done

**Pull request merged**
